# Generated by Django 3.2.9 on 2022-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='Merchant ID')),
                ('username', models.CharField(max_length=255, verbose_name='Merchant username')),
                ('password', models.CharField(max_length=255, verbose_name='Merchant password')),
                ('currency', models.CharField(choices=[('051', 'AMD'), ('978', 'EUR'), ('840', 'USD'), ('643', 'RUB')], default='AMD', max_length=3, null=True, verbose_name='Transaction currency')),
                ('description', models.TextField(verbose_name='Description of the transaction')),
                ('order_id', models.IntegerField(verbose_name='Unique ID of the transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment amount')),
                ('back_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address on the merchant’s server for returning after payment')),
                ('opaque', models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional data')),
                ('card_holder_id', models.IntegerField(blank=True, null=True, verbose_name='Unique ID for binding transactions')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('response_code', models.CharField(max_length=50)),
                ('response_message', models.TextField()),
            ],
        ),
    ]
