# Generated by Django 3.2.9 on 2022-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Merchant ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Merchant password'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Merchant username'),
        ),
    ]
