# Generated by Django 3.2.9 on 2022-03-22 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_auto_20220318_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Գումար')),
                ('order_id', models.IntegerField(verbose_name='Պատվերի հերթական համար')),
                ('payment_id', models.IntegerField(verbose_name='Վճարման հերթական համար')),
                ('response_code', models.CharField(max_length=50, verbose_name='Գործառնության պատասխանի կոդ')),
                ('response_message', models.TextField(verbose_name='Գործառնության պատասխանի նկարագիր')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Օգտագործող')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentResponse',
        ),
    ]
