# Generated by Django 3.2.9 on 2022-03-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20220322_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Գումար'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Պատվերի հերթական համար'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='payment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Վճարման հերթական համար'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='response_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Գործառնության պատասխանի կոդ'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='response_message',
            field=models.TextField(blank=True, null=True, verbose_name='Գործառնության պատասխանի նկարագիր'),
        ),
    ]
