# Generated by Django 3.2.9 on 2022-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_paymentdata_response_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='payment_id',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Վճարման հերթական համար'),
        ),
    ]
