# Generated by Django 3.2.9 on 2022-03-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymentdata_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Պատվերի հերթական համար'),
        ),
    ]
