# Generated by Django 3.2.9 on 2022-03-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20220322_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdata',
            name='order',
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Պատվերի հերթական համար'),
        ),
    ]
