# Generated by Django 3.2.9 on 2022-03-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_order_pay'),
        ('payment', '0009_auto_20220322_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdata',
            name='order_id',
        ),
        migrations.AddField(
            model_name='paymentdata',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Պատվերի հերթական համար'),
        ),
    ]
