# Generated by Django 3.2.9 on 2022-03-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_order_pay'),
        ('payment', '0010_auto_20220323_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdata',
            name='amount_refund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Գումար'),
        ),
        migrations.AlterField(
            model_name='paymentdata',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='main.order', verbose_name='Պատվերի հերթական համար'),
        ),
    ]
