# Generated by Django 3.2.9 on 2022-01-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('address_hy', models.CharField(max_length=255, null=True)),
                ('address_ru', models.CharField(max_length=255, null=True)),
                ('address_en', models.CharField(max_length=255, null=True)),
                ('phone_number_1', models.CharField(max_length=50)),
                ('phone_number_2', models.CharField(blank=True, max_length=50)),
                ('phone_number_3', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Անուն')),
                ('lastname', models.CharField(max_length=100, verbose_name='Ազգանուն')),
                ('email', models.EmailField(max_length=254, verbose_name='Էլեկտրոնային հասցե')),
                ('message', models.TextField(verbose_name='Նամակ')),
                ('file', models.FileField(blank=True, upload_to='files', verbose_name='Ֆայլ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծվոլ է')),
            ],
            options={
                'verbose_name': 'Նամակ',
                'verbose_name_plural': 'Նամակներ',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_hy', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_hy', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='about_order')),
            ],
        ),
    ]
