# Generated by Django 3.2.9 on 2021-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_aboutcontact_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='termsorder',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsorder',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsorder',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsorder',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='termsorder',
            name='title_hy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='termsorder',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
