# Generated by Django 3.2.9 on 2022-01-22 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Կատեգորիա')),
                ('title_hy', models.CharField(max_length=250, null=True, verbose_name='Կատեգորիա')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='Կատեգորիա')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Կատեգորիա')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Նկար')),
                ('url', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Կաեգորիա',
                'verbose_name_plural': 'Կատեգորիաներ',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Հեռախոսահամար')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Հասցե')),
                ('address_hy', models.TextField(blank=True, null=True, verbose_name='Հասցե')),
                ('address_ru', models.TextField(blank=True, null=True, verbose_name='Հասցե')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='Հասցե')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Օգտագործող')),
                ('user_en', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Օգտագործող')),
                ('user_hy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Օգտագործող')),
                ('user_ru', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Օգտագործող')),
            ],
            options={
                'verbose_name': 'Օգտագործող',
                'verbose_name_plural': 'Օգտագործողներ',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Չափման միավոր')),
                ('type_hy', models.CharField(max_length=50, null=True, verbose_name='Չափման միավոր')),
                ('type_ru', models.CharField(max_length=50, null=True, verbose_name='Չափման միավոր')),
                ('type_en', models.CharField(max_length=50, null=True, verbose_name='Չափման միավոր')),
            ],
            options={
                'verbose_name': 'Չափման միավոր',
                'verbose_name_plural': 'Չափման միավորներ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ավելացվել է')),
                ('finale_price', models.PositiveIntegerField(default=0, verbose_name='Ընդհանուր գումար')),
                ('delivery_cost', models.PositiveIntegerField(default=0, verbose_name='Առաքման արժեք')),
                ('status', models.CharField(choices=[('STATUS_NEW', 'Նոր պատվեր'), ('STATUS_READY', 'Պատվերը պատրաստ է'), ('STATUS_COMPLETED', 'Պատվերը առաքված է')], default='STATUS_NEW', max_length=100)),
                ('status_hy', models.CharField(choices=[('STATUS_NEW', 'Նոր պատվեր'), ('STATUS_READY', 'Պատվերը պատրաստ է'), ('STATUS_COMPLETED', 'Պատվերը առաքված է')], default='STATUS_NEW', max_length=100, null=True)),
                ('status_ru', models.CharField(choices=[('STATUS_NEW', 'Նոր պատվեր'), ('STATUS_READY', 'Պատվերը պատրաստ է'), ('STATUS_COMPLETED', 'Պատվերը առաքված է')], default='STATUS_NEW', max_length=100, null=True)),
                ('status_en', models.CharField(choices=[('STATUS_NEW', 'Նոր պատվեր'), ('STATUS_READY', 'Պատվերը պատրաստ է'), ('STATUS_COMPLETED', 'Պատվերը առաքված է')], default='STATUS_NEW', max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Պատվեր կատարող')),
                ('customer_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Պատվեր կատարող')),
                ('customer_hy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Պատվեր կատարող')),
                ('customer_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Պատվեր կատարող')),
            ],
            options={
                'verbose_name': 'Պատվեր',
                'verbose_name_plural': 'Պատվերներ',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Անուն')),
                ('title_hy', models.CharField(max_length=255, null=True, verbose_name='Անուն')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Անուն')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Անուն')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Նկար')),
                ('url', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Նկարագրություն')),
                ('description_hy', models.TextField(null=True, verbose_name='Նկարագրություն')),
                ('description_ru', models.TextField(null=True, verbose_name='Նկարագրություն')),
                ('description_en', models.TextField(null=True, verbose_name='Նկարագրություն')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Գին')),
                ('new_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Նոր գին')),
                ('start_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Սկզբնական չափ')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա')),
                ('category_en', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա')),
                ('category_hy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա')),
                ('category_ru', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա')),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measurement', verbose_name='Չափման միավոր')),
                ('measurement_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measurement', verbose_name='Չափման միավոր')),
                ('measurement_hy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measurement', verbose_name='Չափման միավոր')),
                ('measurement_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measurement', verbose_name='Չափման միավոր')),
            ],
            options={
                'verbose_name': 'Ապրանք',
                'verbose_name_plural': 'Ապրանքներ',
            },
        ),
        migrations.CreateModel(
            name='Time_Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_shipping', models.CharField(max_length=100, verbose_name='Առաքման ժամ')),
            ],
            options={
                'verbose_name': 'Առաքման ժամ',
                'verbose_name_plural': 'Առաքման ժամեր',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Քաղաք')),
                ('city_hy', models.CharField(max_length=200, null=True, verbose_name='Քաղաք')),
                ('city_ru', models.CharField(max_length=200, null=True, verbose_name='Քաղաք')),
                ('city_en', models.CharField(max_length=200, null=True, verbose_name='Քաղաք')),
                ('address', models.CharField(max_length=200, verbose_name='Հասցե')),
                ('address_hy', models.CharField(max_length=200, null=True, verbose_name='Հասցե')),
                ('address_ru', models.CharField(max_length=200, null=True, verbose_name='Հասցե')),
                ('address_en', models.CharField(max_length=200, null=True, verbose_name='Հասցե')),
                ('phone', models.CharField(max_length=100, verbose_name='Հեռախոսահամար')),
                ('date_shipping', models.DateField(null=True, verbose_name='Առաքման օր')),
                ('payment_type', models.CharField(choices=[('TYPE_PAYMENT_CASH', 'Կանխիկ'), ('TYPE_PAYMENT_NON_CASH', 'Անկանխիկ')], max_length=100, null=True)),
                ('payment_type_hy', models.CharField(choices=[('TYPE_PAYMENT_CASH', 'Կանխիկ'), ('TYPE_PAYMENT_NON_CASH', 'Անկանխիկ')], max_length=100, null=True)),
                ('payment_type_ru', models.CharField(choices=[('TYPE_PAYMENT_CASH', 'Կանխիկ'), ('TYPE_PAYMENT_NON_CASH', 'Անկանխիկ')], max_length=100, null=True)),
                ('payment_type_en', models.CharField(choices=[('TYPE_PAYMENT_CASH', 'Կանխիկ'), ('TYPE_PAYMENT_NON_CASH', 'Անկանխիկ')], max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer', verbose_name='Պատվիրատու')),
                ('customer_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer', verbose_name='Պատվիրատու')),
                ('customer_hy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer', verbose_name='Պատվիրատու')),
                ('customer_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer', verbose_name='Պատվիրատու')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Պատվեր')),
                ('order_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Պատվեր')),
                ('order_hy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Պատվեր')),
                ('order_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Պատվեր')),
                ('time_shipping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.time_shipping', verbose_name='Առաքման ժամ')),
            ],
            options={
                'verbose_name': 'Առաքում',
                'verbose_name_plural': 'Առաքումներ',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Քանակ')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Օգտագործող')),
                ('customer_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Օգտագործող')),
                ('customer_hy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Օգտագործող')),
                ('customer_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Օգտագործող')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Ապրանք')),
                ('product_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Ապրանք')),
                ('product_hy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Ապրանք')),
                ('product_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Ապրանք')),
            ],
            options={
                'verbose_name': 'Ընտրված ապրանք',
                'verbose_name_plural': 'Ընտրված ապրանքներ',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product_items',
            field=models.ManyToManyField(to='main.ProductItem', verbose_name='Պատվերի ապրանքներ'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Նկար')),
                ('gallery', models.BooleanField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='ապրանք')),
                ('product_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='ապրանք')),
                ('product_hy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='ապրանք')),
                ('product_ru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='ապրանք')),
            ],
            options={
                'verbose_name': 'Նկար',
                'verbose_name_plural': 'Նկարներ',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.PositiveIntegerField(default=0, verbose_name='Առաքման արժեքը')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='main.customer', verbose_name='Օգտագործող')),
                ('customer_en', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='main.customer', verbose_name='Օգտագործող')),
                ('customer_hy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='main.customer', verbose_name='Օգտագործող')),
                ('customer_ru', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='main.customer', verbose_name='Օգտագործող')),
                ('productItems', models.ManyToManyField(blank=True, related_name='product_item', to='main.ProductItem', verbose_name='Զամբյուղի ապրանք')),
            ],
            options={
                'verbose_name': 'Զամբյուղ',
                'verbose_name_plural': 'Զամբյուղներ',
                'ordering': ['-id'],
            },
        ),
    ]
