# Generated by Django 3.2.9 on 2022-01-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='main.Order', verbose_name='Պատվերներ'),
        ),
    ]
