# Generated by Django 3.2.9 on 2022-01-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['date_time_shipping'], 'verbose_name': 'Առաքում', 'verbose_name_plural': 'Առաքումներ'},
        ),
    ]
