# Generated by Django 3.2.9 on 2022-01-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Կանխիկ', 'cash'), ('անկանխիկ', 'non cash')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Նոր պատվեր', 'new order'), ('Պատվերը պատրաստ է', 'order is ready'), ('Պատվերը առաքված է', 'order complated')], default='Նոր պատվեր', max_length=100),
        ),
    ]
