# Generated by Django 3.2.9 on 2021-12-18 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='productItems',
            field=models.ManyToManyField(blank=True, related_name='product_item', to='main.ProductItem'),
        ),
    ]
