# Generated by Django 3.2.9 on 2022-01-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shipping_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ապրանք', 'verbose_name_plural': 'Ապրանքներ'},
        ),
    ]
