# Generated by Django 3.2.9 on 2022-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220202_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Պատվերի մինիմալ չափ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_quantity',
            field=models.IntegerField(default=1, verbose_name='Սկզբնական չափ'),
        ),
    ]
