# Generated by Django 3.2.9 on 2022-01-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_type',
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
