# Generated by Django 3.2.9 on 2022-01-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220119_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measurement_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='measurement_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='start_quantity_item',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Սկզբնական չափ (հատ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Սկզբնական չափ (կգ)'),
        ),
    ]
