# Generated by Django 3.2.9 on 2022-01-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220120_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Վաճարման տարբերակ')),
            ],
            options={
                'verbose_name': 'Վաճարման տարբերակ',
                'verbose_name_plural': 'Վաճարման տարբերակներ',
            },
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Չափման միավոր', 'verbose_name_plural': 'Չափման միավորներ'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='shipping',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.payment_type'),
        ),
    ]
