# Generated by Django 3.2.9 on 2022-01-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_hy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_hy',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_hy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='basket',
            name='delivery_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='finale_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
