# Generated by Django 3.2.9 on 2022-01-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220120_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_type',
            name='button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment_type',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/payment_icon'),
        ),
    ]
