# Generated by Django 3.2.9 on 2021-12-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_productitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
