# Generated by Django 3.2.9 on 2022-01-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_productitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Չափման միավոր')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_quantity_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start_quantity_kg',
        ),
        migrations.AddField(
            model_name='product',
            name='start_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Սկզբնական չափ'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measurement', verbose_name='Չափման միավոր'),
        ),
    ]
