# Generated by Django 3.2.9 on 2022-01-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220120_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time_shipping',
            options={'verbose_name': 'Առաքման ժամ', 'verbose_name_plural': 'Առաքման ժամեր'},
        ),
        migrations.AlterField(
            model_name='shipping',
            name='payment_type',
            field=models.CharField(choices=[('TYPE_PAYMENT_CASH', 'Կանխիկ'), ('TYPE_PAYMENT_NON_CASH', 'Անկանխիկ')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Payment_Type',
        ),
    ]
