# Generated by Django 3.2.9 on 2022-01-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220117_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Քանակ'),
        ),
    ]
