# Generated by Django 3.2.9 on 2021-12-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_productitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
