# Generated by Django 3.2.9 on 2022-02-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
