# Generated by Django 3.2.9 on 2022-01-22 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20220120_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='customer_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='main.customer', verbose_name='Օգտագործող'),
        ),
        migrations.AddField(
            model_name='basket',
            name='customer_hy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='main.customer', verbose_name='Օգտագործող'),
        ),
        migrations.AddField(
            model_name='basket',
            name='customer_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='main.customer', verbose_name='Օգտագործող'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Կատեգորիա'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_hy',
            field=models.CharField(max_length=250, null=True, verbose_name='Կատեգորիա'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Կատեգորիա'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Հասցե'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Հասցե'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Հասցե'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Օգտագործող'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_hy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Օգտագործող'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Օգտագործող'),
        ),
        migrations.AddField(
            model_name='image',
            name='product_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='ապրանք'),
        ),
        migrations.AddField(
            model_name='image',
            name='product_hy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='ապրանք'),
        ),
        migrations.AddField(
            model_name='image',
            name='product_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='ապրանք'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='type_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Չափման միավոր'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='type_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Չափման միավոր'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='type_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Չափման միավոր'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Պատվեր կատարող'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Պատվեր կատարող'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Պատվեր կատարող'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('STATUS_NEW', 'Նոր պատվեր'), ('STATUS_READY', 'Պատվերը պատրաստ է'), ('STATUS_COMPLETED', 'Պատվերը առաքված է')], default='STATUS_NEW', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_hy',
            field=models.CharField(choices=[('STATUS_NEW', 'Նոր պատվեր'), ('STATUS_READY', 'Պատվերը պատրաստ է'), ('STATUS_COMPLETED', 'Պատվերը առաքված է')], default='STATUS_NEW', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_ru',
            field=models.CharField(choices=[('STATUS_NEW', 'Նոր պատվեր'), ('STATUS_READY', 'Պատվերը պատրաստ է'), ('STATUS_COMPLETED', 'Պատվերը առաքված է')], default='STATUS_NEW', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_hy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Նկարագրություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hy',
            field=models.TextField(null=True, verbose_name='Նկարագրություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Նկարագրություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measurement', verbose_name='Չափման միավոր'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measurement', verbose_name='Չափման միավոր'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.measurement', verbose_name='Չափման միավոր'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='customer_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Օգտագործող'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='customer_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Օգտագործող'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='customer_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Օգտագործող'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Ապրանք'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Ապրանք'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Ապրանք'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='address_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Հասցե'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='address_hy',
            field=models.CharField(max_length=200, null=True, verbose_name='Հասցե'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='address_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Հասցե'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='city_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Քաղաք'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='city_hy',
            field=models.CharField(max_length=200, null=True, verbose_name='Քաղաք'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='city_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Քաղաք'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer', verbose_name='Պատվիրատու'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer', verbose_name='Պատվիրատու'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer', verbose_name='Պատվիրատու'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='order_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Պատվեր'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='order_hy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Պատվեր'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='order_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order', verbose_name='Պատվեր'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='payment_type_en',
            field=models.CharField(choices=[('TYPE_PAYMENT_CASH', 'Կանխիկ'), ('TYPE_PAYMENT_NON_CASH', 'Անկանխիկ')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='payment_type_hy',
            field=models.CharField(choices=[('TYPE_PAYMENT_CASH', 'Կանխիկ'), ('TYPE_PAYMENT_NON_CASH', 'Անկանխիկ')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='payment_type_ru',
            field=models.CharField(choices=[('TYPE_PAYMENT_CASH', 'Կանխիկ'), ('TYPE_PAYMENT_NON_CASH', 'Անկանխիկ')], max_length=100, null=True),
        ),
    ]
