# Generated by Django 3.2.9 on 2022-02-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productitem_wholesale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_items',
        ),
        migrations.AddField(
            model_name='productitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Պատվեր'),
        ),
    ]
