# Generated by Django 3.2.9 on 2021-12-20 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211220_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_hy',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_hy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Կատեգորիա'),
        ),
    ]
