# Generated by Django 3.2.9 on 2022-02-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220204_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_items',
        ),
    ]
