# Generated by Django 3.2.9 on 2022-02-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_product_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_items',
        ),
        migrations.AddField(
            model_name='productitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='main.order', verbose_name='Պատվեր'),
        ),
    ]
