# Generated by Django 3.2.9 on 2022-02-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_wholesale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'verbose_name': 'Օգտագործող', 'verbose_name_plural': 'Օգտագործողներ'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_added'], 'verbose_name': 'Պատվեր', 'verbose_name_plural': 'Պատվերներ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Ապրանք', 'verbose_name_plural': 'Ապրանքներ'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='basket',
            name='session_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='main.customer', verbose_name='Օգտագործող'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Օգտագործող'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='wholesale',
            field=models.BooleanField(default=False, verbose_name='Մեծածախ'),
        ),
    ]
