# Generated by Django 3.2.9 on 2022-02-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220207_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_order_quantity',
            new_name='min_order_qty',
        ),
    ]
