# Generated by Django 3.2.9 on 2022-02-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_min_order_quantity_product_min_order_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_order_qty',
            new_name='min_order_quantity',
        ),
    ]
