# Generated by Django 3.2.9 on 2022-02-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_min_order_qty_product_min_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Կաեգորիա', 'verbose_name_plural': 'Կատեգորիաներ'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_shipping', 'time_shipping'], 'verbose_name': 'Պատվեր', 'verbose_name_plural': 'Պատվերներ'},
        ),
    ]
