# Generated by Django 3.2.9 on 2022-03-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_productitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Հասցե'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Հասցե'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_hy',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Հասցե'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Հասցե'),
        ),
    ]
