# Generated by Django 3.2.9 on 2022-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220302_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Պատվերի մինիմալ չափ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Նոր գին'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Գին'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Սկզբնական չափ'),
        ),
    ]
