# Generated by Django 3.2.9 on 2022-03-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220303_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Պատվերի մինիմալ չափ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Սկզբնական չափ'),
        ),
    ]
