# Generated by Django 3.2.9 on 2022-03-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220303_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Նկար \n (Ոչ պակաս քան 400*400)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Պատվերի մինիմալ չափ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Ավելացման/պակասեցման չափ'),
        ),
    ]
