# Generated by Django 3.2.9 on 2022-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20220310_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Գին'),
        ),
    ]
