# Generated by Django 3.2.9 on 2022-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_productitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Գին'),
        ),
    ]
