# Generated by Django 3.2.9 on 2022-03-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_productitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('PAID', 'Վճարված է'), ('NOT PAID', 'Վճարված չէ')], default='NOT PAID', max_length=10, verbose_name='Վճարման կարգավիճակ'),
        ),
    ]
