# Generated by Django 3.2.9 on 2022-03-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_order_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Հետ վերադարձվող գումարի չափ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('PAID', 'Վճարված է'), ('NOT PAID', 'Վճարված չէ'), ('CANCEL', 'Չեղարկված'), ('REFUND', 'Հետ վերադարձ')], default='NOT PAID', max_length=10, verbose_name='Վճարման կարգավիճակ'),
        ),
    ]
