# Generated by Django 3.2.9 on 2022-03-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20220322_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Հետ վերադարձվող գումարի չափ, եթե արկա է։'),
        ),
    ]
