# Generated by Django 3.2.9 on 2022-03-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_order_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('PAID', 'Վճարված է'), ('NOT_PAID', 'Վճարված չէ'), ('CANCEL', 'Չեղարկված'), ('REFUND', 'Հետ վերադարձ')], default='NOT PAID', max_length=10, verbose_name='Վճարման կարգավիճակ'),
        ),
    ]
