# Generated by Django 3.2.9 on 2022-04-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_order_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('PAID', 'Վճարված է'), ('NOT_PAID', 'Վճարված չէ'), ('CANCEL', 'Չեղարկված'), ('REFUND', 'Հետ վերադարձ'), ('FAILED', 'Ձախողված')], default='NOT PAID', max_length=10, verbose_name='Վճարման կարգավիճակ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('STATUS_NEW', 'Նոր պատվեր'), ('STATUS_READY', 'Պատվերը պատրաստ է'), ('STATUS_COMPLETED', 'Պատվերը առաքված է'), ('CANCEL', 'Չեղարկված')], default='STATUS_NEW', max_length=100),
        ),
    ]
