# Generated by Django 3.2.9 on 2022-04-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20220401_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('PAID', 'Վճարված է'), ('NOT_PAID', 'Վճարված չէ'), ('CANCEL', 'Չեղարկված'), ('REFUND', 'Հետ վերադարձ'), ('FAILED', 'Ձախողված')], default='NOT_PAID', max_length=10, verbose_name='Վճարման կարգավիճակ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('TYPE_PAYMENT_CASH', 'Կանխիկ')], max_length=100, null=True),
        ),
    ]
